name: tutorialenv
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.23.0
  - jupyterlab=3.6.3
  - matplotlib=3.7.1
  - numpy=1.24.3
  - pandas=1.5.3
  - python=3.11.4
  - xarray=2023.6.0
  - netcdf4=1.6.5
  - scikit-learn=1.3.0
  - statsmodels=0.14.0 
  - dask=2023.6.0 
  - zarr=2.8.3
  - s3fs=2023.4.0
  - fsspec=2023.4.0 
  - hvplot=0.8.4
  - wget=1.20.3
  - aiohttp=3.8.3
  - geoviews=1.9.2