name: tutorialenv
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.23.0
  - jupyterlab=3.6.3
  - matplotlib=3.7.1
  - numpy=1.24.3
  - pandas=1.5.3
  - python=3.11.4
  - xarray=2023.6.0
  - netcdf4=1.6.5
  - dask=2023.6.0 