name: tutorialenv
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.18.0
  - jupyterlab=2.2.8
  - matplotlib=3.2.2
  - numpy=1.18.5
  - pandas=1.0.5
  - python=3.7.6
  - xarray=0.15.1
  - netcdf4=1.5.3
  - scikit-learn=1.0
  - statsmodels=0.13.0 
  - dask=2.19.0 
  - zarr=2.8.3
  - s3fs=0.2.0
  - fsspec=2021.8.1 
  - hvplot=0.7.3
  - wget=1.20.3
  - aiohttp=3.7.4.post0
  - geoviews=1.9.2
